# Generated by Django 2.0 on 2018-01-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['due_back'], 'permissions': []},
        ),
    ]
