# Generated by Django 2.0 on 2018-01-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180115_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['due_back'], 'permissions': [('delete_books', 'Can delete books')]},
        ),
    ]
