# Generated by Django 2.0 on 2018-01-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180115_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['due_back'], 'permissions': [('delete_books', 'delete_books')]},
        ),
    ]
